---
title: "Complemento al curso Introducción al software estadístico R: Jamovi"
author: "Emilio L. Cano"
date: 2025-01-14
format: html
toc: true
lang: es-ES
---

## Alcance

Este documento contiene material complementario al curso [Introducción al software estadístico R](https://www.lcano.com/b/iser/slides_elcano/) que imparto en distintas instituciones.

[Jamovi](https://www.jamovi.org/features.html) es una plataforma estadística abierta, que utiliza el software estadístico y lenguaje de programación R para ejecutar los análisis estadísticos. Es un software gratuito aunque con algunas limitaciones. Existen planes para superar esas limitaciones.

Se puede utilizar en la nube o como aplicación de escritorio, y existe documentación disponible de buena calidad, entre la que destacan:

1.  Libro [learning statistics with jamovi](https://davidfoxcroft.github.io/lsj-book/)

2.  [Documentación oficial](https://jamovi.readthedocs.io/es/latest/). Algunas páginas traducidas al español.

3.  [Curso gratuito en datalab.cc](https://datalab.cc/jamovi/)

## Instalación de Jamovi. Módulos

### Jamovi Cloud

Solo hace falta tener una cuenta en Jamovi, que se puede vincular a una cuenta de Google. Iniciar sesión en <https://www.jamovi.org/cloud.html>

### Jamovi Desktop

1.  Ir a la página de descargas <https://www.jamovi.org/download.html>

2.  Descargar el archivo para Windows o para MacOS (o seguir instrucciones para Linux)

3.  Instalar de la forma habitual

### Jamovi modules

Jamovi contiene una funcionalida básica por defecto. Pero también tiene un sistema de extensiones, similar a los paquetes de R que la comunidad comparte, y que extiende la funcionalidad.

1.  Haz clic en el icono "Módulos"

2.  Ve a la **Biblioteca jamovi**

3.  Explora los módulos

4.  Prueba alguno (por ejemplo, distrACTION)

### Estructura de la apliación

-   Menú superior

-   Menús de datos, análisis e informe

-   Opciones menú derecho

## Ver y ejecutar código Jamovi en R

-   Documentación: [Jamovi and R](https://jamovi.readthedocs.io/pt/latest/usermanual/um_6_jamovi_and_R.html)

-   Activar Syntax mode en las opciones

-   Instalar paquetes necesarios

-   Usar el código de Jamovi en R

```{r}

library(jmv)
jmv::descriptives(data = iris)
```

## Ver y ejecutar código R en Jamovi

Para ejecutar código R en Jamovi, debemos instalar el módulo Rj Editor. Se crea un icono en el menú de Análisis, que abre un editor que funciona como la consola de R. Podemos así añadir nuestros propios análisis con paquetes que no estén disponibles en Jamovi.

:::{.callout-warning}

## Cuidado

En la versión cloud no se puede instalar este módulo con el plan gratuito.

:::

## Importación y transformación de datos con Jamovi

Jamovi detecta automáticamente archivos de datos de diversos tipos (excel, rds, csv, ...). Para abrir un archivo de datos, vamos al menú principal arriba a la izquierda y seleccionamos "Abrir". Navegamos hasta la carpeta donde está el archivo de datos y seleccionamos el archivo de datos.

El menú Importar especial permite seleccionar el tipo de archivo.

En el menú Exportar podemos exportar nuestro archivo a los formatos más populares, incluido excel y R.

:::{.callout-warning}
Jamovi solo trabaja con un conjunto de datos cada vez, por lo que si queremos consolidar varios archivos en uno, lo tendremos que hacer con código R u otro software.
:::

Para transformar los datos cargados en Jamovi, utilizamos el menú Variables.

* Botón Editar: Para modificar la columna seleccionada
* Botón Calcular: Para añadir variables calculadas
* Botón Transformar: Para recodificar una variable
* Botón Filtros: Para filtrar por variable. Una vez aplicado el filtro, las operaciones de análisis se realizan sobre los datos filtrados, no sobre los datos completos. Para guardar los datos filtrados, tendríamos que hacerlo en el editor de código de R, ya que no hay una opción para quedarse solo con los datos filtrados. No obstante, podemos copiar los datos filtrados y pegarlos directamente en Excel.
* Botones Agregar y Eliminar: Para agregar y eliminar columnas

En el menú Datos tenemos también todas estas opciones, seleccionando las columnas en una lista y no en la tabla de datos. Además, tenemos botones para añadir y eliminar **filas**.

:::{.callout-tip}
Una forma de quedarnos con los datos filtrados y poder exportarlos, sería haciendo el filro opuesto y eliminar las filas filtradas.
:::

## Exploración de datos con Jamovi

La funcionalidad para análisis exploratorio que hemos visto con R la encontramos repartida en los módulos Exploración y Regresión.

### Análisis exploratorio de una variable

* Exploración/Descriptivas: 
  + Seleccionamos la variable que queremos explorar.
  + Si es cualitativa, seleccionamos Tabla de Frecuencias y Gráfico de barras
  + Si es cuantitativa, seleccionamos los estadísticos resumen a mostrar y los gráficos que queramos (histograma, gráfico de cajas, violin)
  
### Análisis exploratorio de varias variables

* Exploración/Descriptivas:
  + Para comparar cuantitativa según niveles de cualitativa: seleccionar la variable cuantitativa y añadir la variable cualitativa a "Separa por"
  + Para comparar dos cualitativas, añadir una a variables y otra a "Separa por"

* Exploración/Dispersión:
  + Para comparar dos cuantitativas: Añade una a cada eje.
  + Para comparar dos cuantitativas + una cualitativa, añade esta última a "Grupo"

* Regresión/Matriz de correlaciones:
  * Añade variables numéricas
  * Marca la gráfica para obtener la matriz de gráficos por pares como la vista con R

## Análisis de atributos con Jamovi

## Regresión con Jamovi

## Prueba t y ANOVA con Jamovi

## El modelo de fórmulas de R
